variables:
   DEV_USERNAME: deployment
   DEV_SERVER_IP: 10.1.100.225

   PROD_EXTENSION_USERNAME: deployment
   PROD_EXTENSION_SERVER_IP: 10.1.100.166


image: node:11

cache:
    paths:
    - node_modules/

stages:
   - build
   - deploy

### BUILDS

buildProdExtension:
  stage: build
  
  only:
    - extension
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive readium-js    
  script:
  - LAST_TAG=$(git describe --tags | cut -d '-' -f1)
  - sed -i "s/0\.31\.1/$LAST_TAG/" package.json    
  # Yaml doesn't like ':<space>' wrap command in quotes
  # - "sed -i \"s/lrsCredential: \'.*\'/lrsCredential: \'$PROD_EXTENSION_LRS_AUTH\'/g\" src/js/pebl-login-widget.js"
  # - "sed -i \"s/production: false/production: true/g\" src/mixins/config.js"
  - sed -i "s/TIMESTAMPMERIGHTHERE/$(date)/" src/cloud-reader/offlinePebl.appcache
  - echo "window.Configuration = {};" > src/cloud-reader/config.js
  - echo "window.Configuration.lrsUrl = '$PROD_EXTENSION_LRS_URL';" >> src/cloud-reader/config.js
  - echo "window.Configuration.lrsCredential = '$PROD_EXTENSION_LRS_CREDENTIAL';" >> src/cloud-reader/config.js
  - echo "window.Configuration.useLinkedIn = true;" >> src/cloud-reader/config.js
  - echo "window.Configuration.favicon = 'images/eXtension-icon_small.png';" >> src/cloud-reader/config.js
  - echo "window.Configuration.loginImage = 'images/eXtension-black.png';" >> src/cloud-reader/config.js

  - echo "{" > src/i18n/_locales/en_US/skinning.json

  - "echo '\"i18n_pebl_library\" : { \"message\" : \"eXtension Library\" },' >> src/i18n/_locales/en_US/skinning.json"
  - "echo '\"i18n_pebl_reader\" : { \"message\" : \"eXtension Reader\" },' >> src/i18n/_locales/en_US/skinning.json"
  - "echo '\"i18n_pebl_title\" : { \"message\" : \"eXtension Foundation\" },' >> src/i18n/_locales/en_US/skinning.json"
  - "echo '\"i18n_pebl_webreader_logo\" : { \"message\" : \"images/eXtension-icon_small.png\" }' >> src/i18n/_locales/en_US/skinning.json"
  
  - echo "}" >> src/i18n/_locales/en_US/skinning.json
  
  - npm run prepare:all
  - npm run dist
  artifacts:
    paths:
      - dist/cloud-reader
    
  
buildProd:
  stage: build

  only:
    - master
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive readium-js    
  script:
  - LAST_TAG=$(git describe --tags | cut -d '-' -f1)
  - sed -i "s/0\.31\.1/$LAST_TAG/" package.json    
  # Yaml doesn't like ':<space>' wrap command in quotes
  # - "sed -i \"s/lrsCredential: \'.*\'/lrsCredential: \'$PROD_LRS_AUTH\'/g\" src/js/pebl-login-widget.js"  
  # - "sed -i \"s/production: false/production: true/g\" src/mixins/config.js"
  - sed -i "s/TIMESTAMPMERIGHTHERE/$(date)/" src/cloud-reader/offlinePebl.appcache
  - echo "window.Configuration = {};" > src/cloud-reader/config.js
  - echo "window.Configuration.lrsUrl = '$PROD_LRS_URL';" >> src/cloud-reader/config.js
  - echo "window.Configuration.lrsCredential = '$PROD_LRS_CREDENTIAL';" >> src/cloud-reader/config.js
  - echo "window.Configuration.useLinkedIn = false;" >> src/cloud-reader/config.js
  - echo "window.Configuration.loginImage = 'images/PEBL-Logo-Color-small.png';" >> src/cloud-reader/config.js

  - npm run prepare:all
  - npm run dist
  artifacts:
    paths:
    - dist/cloud-reader

buildQA:
  stage: build 

  only:
    - QA
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive readium-js    
  script:  
  - LAST_TAG=$(git describe --tags | cut -d '-' -f1)
  - sed -i "s/0\.31\.1/$LAST_TAG/" package.json
  - sed -i "s/TIMESTAMPMERIGHTHERE/$(date)/" src/cloud-reader/offlinePebl.appcache
  
  - echo "window.Configuration = {};" > src/cloud-reader/config.js
  - echo "window.Configuration.lrsUrl = '$QA_LRS_URL';" >> src/cloud-reader/config.js
  - echo "window.Configuration.lrsCredential = '$QA_LRS_CREDENTIAL';" >> src/cloud-reader/config.js
  - echo "window.Configuration.useLinkedIn = false;" >> src/cloud-reader/config.js
  - echo "window.Configuration.loginImage = 'images/PEBL-Logo-Color-small.png';" >> src/cloud-reader/config.js
  
  - npm run prepare:all
  - npm run dist
  artifacts:
    paths:
    - dist/cloud-reader

buildDev:
  stage: build
  only:
    - Dev
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive readium-js
  script:
  - LAST_TAG=$(git describe --tags)
  - sed -i "s/0\.31\.1/$LAST_TAG/" package.json
  - sed -i "s/TIMESTAMPMERIGHTHERE/$(date)/" src/cloud-reader/offlinePebl.appcache
  
  - npm run prepare:all
  - npm run dist
  artifacts:
    paths:
    - dist/cloud-reader

### DEPLOYMENTS

prodExtensionDeploy:
  stage: deploy
  only:
    - extension
  script:
    ## Pull down apt-get install repos
   - apt-get update -y
   - apt-get install openssh-client -y

   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   ##
   ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
   ## following two lines. NOTE the $SSH_KNOWN_HOSTS variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$PROD_EXTENSION_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   ## NOTE the $STAGINT_PRIVATE_KEY variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$PROD_EXTENSION_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   ## Build commands
   - ssh -p22 $PROD_EXTENSION_USERNAME@$PROD_EXTENSION_SERVER_IP "mv /var/www/html/epub_content /var/www/books/prodBookshelf"
   - ssh -p22 $PROD_EXTENSION_USERNAME@$PROD_EXTENSION_SERVER_IP "rm -rf /var/www/html/*"
   - scp -P22 -r dist/cloud-reader/* $PROD_EXTENSION_USERNAME@$PROD_EXTENSION_SERVER_IP:/var/www/html/
   - ssh -p22 $PROD_EXTENSION_USERNAME@$PROD_EXTENSION_SERVER_IP "mv /var/www/books/prodBookshelf /var/www/html/epub_content"
   
### ----------------------


prodDeploy:
  stage: deploy
  only:
    - master
  script:
    ## Pull down apt-get install repos
   - apt-get update -y
   - apt-get install openssh-client -y

   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   ##
   ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
   ## following two lines. NOTE the $SSH_KNOWN_HOSTS variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   ## NOTE the $STAGINT_PRIVATE_KEY variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   ## Build commands
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "mv /var/www/htmlOrgReaderProd/epub_content /var/www/bookTempDeployment/prodBookshelf"      
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "rm -rf /var/www/htmlOrgReaderProd/*"
   - scp -P22 -r dist/cloud-reader/* $DEV_USERNAME@$DEV_SERVER_IP:/var/www/htmlOrgReaderProd/
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "mv /var/www/bookTempDeployment/prodBookshelf /var/www/htmlOrgReaderProd/epub_content"
   
### ----------------------

qaDeploy:
  stage: deploy
  only:
    - QA
    
  script:
   - apt-get update -y
   - apt-get install openssh-client -y
   ##
   ## Install ssh-agent if not already installed, it is required by Docker.
   ## (change apt-get to yum if you use an RPM-based image)
   ##
   - 'which ssh-agent || apt-get install openssh-client -y'

   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   ##
   ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
   ## following two lines. NOTE the $SSH_KNOWN_HOSTS variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   ## NOTE the $STAGINT_PRIVATE_KEY variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   ## Build commands
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "mv /var/www/htmlOrgReaderQa/epub_content /var/www/bookTempDeployment/qaBookshelf"   
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "rm -rf /var/www/htmlOrgReaderQa/*"
   - scp -P22 -r dist/cloud-reader/* $DEV_USERNAME@$DEV_SERVER_IP:/var/www/htmlOrgReaderQa/
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "mv /var/www/bookTempDeployment/qaBookshelf /var/www/htmlOrgReaderQa/epub_content"

### ----------------------

devDeploy:
  stage: deploy
  only:
    - Dev
  script:
   ## Pull down apt-get install repos
   - apt-get update -y
   - apt-get install openssh-client -y
   ##
   ## Install ssh-agent if not already installed, it is required by Docker.
   ## (change apt-get to yum if you use an RPM-based image)
   ##
   - 'which ssh-agent || apt-get install openssh-client -y'

   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   ##
   ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
   ## following two lines. NOTE the $SSH_KNOWN_HOSTS variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   ## NOTE the $STAGINT_PRIVATE_KEY variable should be added
   ## in the gitlab interface and not here
   ##
   - echo "$DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   ## Build commands
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "mv /var/www/htmlOrgReaderDev/epub_content /var/www/bookTempDeployment/devBookshelf"
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "rm -rf /var/www/htmlOrgReaderDev/*"
   - scp -P22 -r dist/cloud-reader/* $DEV_USERNAME@$DEV_SERVER_IP:/var/www/htmlOrgReaderDev/
   - ssh -p22 $DEV_USERNAME@$DEV_SERVER_IP "mv /var/www/bookTempDeployment/devBookshelf /var/www/htmlOrgReaderDev/epub_content"
